
services:
  server:
    build:
      context: .
      # args:
      #   - NODE_ENV=development
      #   - DATABASE_URL=postgresql://postgres:postgres@db:5432/foca_expresso
    command: yarn dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - database

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
